Twitter_Account_List=data.frame(AppName=c(
  "NameOfYourTwitterApp",
  "NameOfAnotherTwitterAppIfYouHaveOne_DifferentNamesSoYouCanTellOneRowOfValuesFromAnother"),
  Login=c(
    "TwitterHandleAssociatedWith_NameOfYourTwitterApp",
    "TwitterHandleAssociatedWith_YourOtherTwitterApp"),
  ConsumerKey=c(
    "RandomStringTwitterGivesYouForYourTwitterApp",
    "RandomStringTwitterGivesYouForYourOtherTwitterApp"),
  ConsumerSecret=c(
    "AnotherRandomStringTwitterGivesYouForYourTwitterApp",
    "AnotherRandomStringTwitterGivesYouForYourOtherTwitterApp"),
  AccessToken=c(
    "YetAnotherRandomStringTwitterGivesYouForYourTwitterApp",
    "YetAnotherRandomStringTwitterGivesYouForYourOtherTwitterApp"),
  AccessTokenSecret=c(
    "LastAnotherRandomStringTwitterGivesYouForYourTwitterApp",
    "LastAnotherRandomStringTwitterGivesYouForYourOtherTwitterApp"),
  stringsAsFactors=FALSE)